import { Job } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior React Developer",
    company: "TechCorp",
    location: "San Francisco, CA",
    salary: {
      min: 120000,
      max: 160000,
      currency: "USD",
    },
    matchScore: 0.85,
    description:
      "We are looking for an experienced React developer to join our growing team. You will work on cutting-edge web applications.",
    requiredSkills: ["React", "TypeScript", "Node.js", "Redux", "Jest"],
    benefits: ["Health Insurance", "401k", "Remote Work", "Stock Options"],
    employmentType: "full-time",
    remote: "hybrid",
    postedAt: new Date().toISOString(),
    link: "https://example.com/job/1",
    companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TC",
    isNew: true,
  },
  {
    id: "2",
    title: "Full Stack Engineer",
    company: "StartupXYZ",
    location: "New York, NY",
    salary: {
      min: 100000,
      max: 140000,
      currency: "USD",
    },
    matchScore: 0.72,
    description:
      "Join our fast-growing startup as a Full Stack Engineer. You'll work with modern tech stack and have direct impact on product.",
    requiredSkills: ["JavaScript", "React", "Python", "PostgreSQL", "AWS"],
    benefits: ["Equity", "Flexible Hours", "Learning Budget", "Wellness"],
    employmentType: "full-time",
    remote: "remote",
    postedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    link: "https://example.com/job/2",
    isNew: true,
  },
  {
    id: "3",
    title: "Backend Engineer - Python",
    company: "DataSystems Inc",
    location: "Seattle, WA",
    salary: {
      min: 110000,
      max: 150000,
      currency: "USD",
    },
    matchScore: 0.65,
    description:
      "We are building scalable backend systems. Join us to work with Python, microservices, and cloud infrastructure.",
    requiredSkills: ["Python", "FastAPI", "PostgreSQL", "Docker", "Kubernetes"],
    benefits: ["Health Insurance", "Gym Membership", "Remote Work"],
    employmentType: "full-time",
    remote: "hybrid",
    postedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    link: "https://example.com/job/3",
    isNew: false,
  },
  {
    id: "4",
    title: "ML Engineer",
    company: "AI Innovations",
    location: "Boston, MA",
    salary: {
      min: 130000,
      max: 180000,
      currency: "USD",
    },
    matchScore: 0.58,
    description:
      "Build machine learning models and deploy them to production. Experience with large-scale data processing required.",
    requiredSkills: ["Python", "TensorFlow", "PyTorch", "SQL", "MLOps"],
    benefits: ["Stock Options", "Conference Budget", "Flexible Schedule"],
    employmentType: "full-time",
    remote: "hybrid",
    postedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    link: "https://example.com/job/4",
    isNew: false,
  },
  {
    id: "5",
    title: "Frontend Engineer - Internship",
    company: "WebWorks",
    location: "Remote",
    salary: {
      min: 20,
      max: 30,
      currency: "USD/hr",
    },
    matchScore: 0.78,
    description:
      "3-month paid internship focused on React and modern frontend development. Great for building portfolio.",
    requiredSkills: ["React", "JavaScript", "CSS", "Git"],
    benefits: ["Mentorship", "Flexible Hours", "Remote"],
    employmentType: "internship",
    remote: "remote",
    postedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    link: "https://example.com/job/5",
    isNew: true,
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "CloudSys",
    location: "Austin, TX",
    salary: {
      min: 115000,
      max: 155000,
      currency: "USD",
    },
    matchScore: 0.45,
    description:
      "We need DevOps expertise to manage our cloud infrastructure and deployment pipelines. Work with AWS, Docker, and Kubernetes.",
    requiredSkills: ["AWS", "Kubernetes", "Docker", "Terraform", "CI/CD"],
    benefits: ["Relocation Assistance", "Stock Options", "Professional Development"],
    employmentType: "full-time",
    remote: "on-site",
    postedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    link: "https://example.com/job/6",
    isNew: false,
  },
];
